In [1]:
import numpy as np

We want to sum a lot of numbers. We could do a function with a loop iterating through a list

In [7]:
def calculator(list_of_numbers):
    result = 0
    for number in list_of_numbers:
        if type(number) == int:
            result = result + number
        else:
            print('ERROR: Wait, a calculator needs numbers, what are you doing?')
    print(f'The result is {result}')        

In [8]:
numbers = [1,2,3,4,5]

In [9]:
calculator(numbers)

The result is 15


But we are iterating through a list, so we are doing a lot of operations!

## Structure from numpy: arrays

In [24]:
np.array(numbers)

array([1, 2, 3, 4, 5])

In [25]:
np.array(numbers)[0]

1

In [61]:
np.array(numbers).shape

(5,)

In [5]:
np.array(numbers).sum()

15

In [10]:
sum(np.array(numbers))

15

In [11]:
def calculator(list_of_numbers):
    result = np.array(numbers).sum()    
    print(f'The result is {result}')  

In [12]:
calculator(numbers)

The result is 15


Let's see some numpy functions

In [15]:
number_array = np.array(numbers)

In [16]:
number_array.sum()

15

In [17]:
number_array.mean()

3.0

In [18]:
def calculator(list_of_numbers, operation):
    result = operation(np.array(numbers))   
    print(f'The result is {result}')  

In [21]:
calculator(numbers, np.sum)

The result is 15


In [22]:
calculator(numbers, np.mean)

The result is 3.0


Now we know that an argument can also be a function.

Let's pass the function an array

In [23]:
def calculator(array_numbers, operation):
    result = operation(array_numbers)   
    print(f'The result is {result}') 

### A better calculator

Now we want to be able to give the calculator also a matrix. Can we do that?

In [26]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
array_matrix = np.array(matrix)
print(array_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


QUESTION: Will it work?

In [30]:
calculator(array_matrix, np.sum)
#Exactly, this is because the type is the same

The result is 45


This is the same as doing `np.sum(array_matrix)`

In [29]:
np.sum(array_matrix)

45

As we now only want to try numpy, let's forget the calculator for a while

Let`s generate a random matrix 

In [43]:
random_matrix = np.random.random((3,3))
random_matrix

array([[0.41316671, 0.67189804, 0.91392086],
       [0.9770872 , 0.37974696, 0.23302052],
       [0.4383714 , 0.62646315, 0.22129077]])

We can do a lot of things

In [44]:
random_matrix.sum()

4.874965604551183

In [45]:
random_matrix.sum(axis=1)

array([1.9989856 , 1.58985467, 1.28612533])

In [47]:
random_matrix.sum(axis=0)

array([1.82862531, 1.67810815, 1.36823215])

In [48]:
random_matrix.mean(axis=0)

array([0.66632853, 0.52995156, 0.42870844])

In [49]:
random_matrix.mean(axis=1)

array([0.66632853, 0.52995156, 0.42870844])

In [51]:
random_matrix.std(axis=0)

array([0.26009748, 0.1283595 , 0.32377964])

### Two matrix operation

In [52]:
random_matrix_1 = np.random.random((3,3))
random_matrix_2 = np.random.random((3,3))


In [53]:
np.add(random_matrix_1, random_matrix_2)

array([[0.62268625, 1.236782  , 0.72216426],
       [1.05942381, 1.16970471, 1.05358553],
       [1.57056733, 1.30892731, 0.91153037]])

In [55]:
np.subtract(random_matrix_1, random_matrix_2)

array([[ 0.2901132 , -0.15378934, -0.26472685],
       [-0.63329042,  0.18316794,  0.83222392],
       [-0.07275304, -0.10704257,  0.75329978]])

In [56]:
np.multiply(random_matrix_1, random_matrix_2)

array([[0.07589313, 0.37649464, 0.11286023],
       [0.18033052, 0.33366466, 0.10436145],
       [0.61534719, 0.42545815, 0.06585676]])

In [57]:
np.divide(random_matrix_1, random_matrix_2)

array([[ 2.74465848,  0.77881128,  0.46351355],
       [ 0.25174562,  1.37133525,  8.51913532],
       [ 0.91145605,  0.84880671, 10.52154424]])

Can you always divide?

In [58]:
Crear una matriz de ceros y dividir, no se puede! Pensar una forma de comprobar si la matriz tiene algún cero.

NameError: name 'zeros' is not defined

In [60]:
random_matrix_1.shape

(3, 3)

In [62]:
zeros = np.array([[0,2,3],[4,5,6],[7,8,9]])


In [63]:
np.divide(random_matrix_1, zeros)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 0.27074816, 0.07623957],
       [0.05326667, 0.13528727, 0.15715079],
       [0.10698674, 0.0751178 , 0.09249056]])

The infinite is like another number for numpy

In [67]:
np.inf

inf

In [70]:
np.isinf(1/0)
#Because is not the numpy function. Numpy knows how to deal with the infinite.

ZeroDivisionError: division by zero

In [71]:
np.isinf(np.divide(1,0))

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


True

How could we program our calculator now? Would be let the user to generate some infs?